version: "3"
  
services:
  bot:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 -m src.run
    image: feedmebot
    container_name: bot_feedme
    env_file: .env
    volumes:
      - .:/app/
      - ./db.sqlite3:/app/db.sqlite3


  